version: 2
jobs:
  build:
    working_directory: ~/tenfren
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.3.822
    steps:
      - checkout
      - restore_cache:
          key: tenfren-{{ checksum "deps.edn" }}
      - run: clojure -Spath -X:test:test-runner
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: tenfren-{{ checksum "deps.edn" }}
      - run: clojure -X:test:test-runner
